### ISSUE TITLE
18和19行的

### ISSUE THREAD

**Issue by niumingyuan** [ne-21/sspanel-automaticcheckin#1]
# 机场地址        self.base_url = 'https://****.net'
18和19行的不知道填什么

**Comment by ne-21** [comment]
填机场地址，比如https://paoluz.net

**Comment by ne-21** [comment]
> # 机场地址 self.base_url = 'https://****.net'
> 18和19行的不知道填什么

填机场地址，比如https://paoluz.net

**Comment by ne-21** [comment]
> # 机场地址 self.base_url = 'https://****.net'
> 18和19行的不知道填什么

self.base_url = 'https://paoluz.net'

**Comment by wy1ng** [comment]
我太单纯了，以为就是民航机场。。。

**Comment by ne-21** [comment]
> 我太单纯了，以为就是民航机场。。。

啊这

**Comment by zunwenzhe** [comment]
这个怎么注册账号，流量怎么用呀，之前没用过这种的。。。
