### ISSUE TITLE
登陆失败吗

### ISSUE THREAD

**Issue by a5234338** [ne-21/sspanel-automaticcheckin#11]
<img width="1177" alt="Snipaste_2020-12-18_21-22-25" src="https://user-images.githubusercontent.com/29723821/102678575-68b56780-41e4-11eb-8531-2aae42fb21b9.png">
这报错也是因为机场登陆验证导致登陆失败吗？明明没有登陆验证啊

**Comment by ne-21** [comment]
> <img alt="Snipaste_2020-12-18_21-22-25" width="1177" src="https://user-images.githubusercontent.com/29723821/102678575-68b56780-41e4-11eb-8531-2aae42fb21b9.png">
> 
> 这报错也是因为机场登陆验证导致登陆失败吗？明明没有登陆验证啊

本人测试无问题
![QQ截图20201221123902.png](https://i.loli.net/2020/12/21/XONJ5pnfY9Ku8C4.png)

**Comment by a5234338** [comment]
你是用的python2.7还是3.6，我俩个都不行

**Comment by a5234338** [comment]
不对，你这不是在云函数执行的？

**Comment by ne-21** [comment]
> 不对，你这不是在云函数执行的？

![QQ截图20201221170402.png](https://i.loli.net/2020/12/21/VvqXS5AaFOsPbN3.png)
你机场的问题，国内ip进不去

**Comment by ne-21** [comment]
> 不对，你这不是在云函数执行的？

![QQ截图20201221170402.png](https://i.loli.net/2020/12/21/VvqXS5AaFOsPbN3.png)

**Comment by a5234338** [comment]
我说呢。那岂不是还得有过墙的环境，云函数肯定就不行了。

**Comment by ne-21** [comment]
> 我说呢。那岂不是还得有过墙的环境，云函数肯定就不行了。

那问题来了，有的不要过墙环境。
