### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by jiangzhe11** [ne-21/sspanel-automaticcheckin#13]
机场地址: [n95cloud.vip](n95cloud.vip)
```
Response: 
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 99, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 92, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 52, in checkin\n    msg = (response.json()).get('msg')\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430}

Output:
START RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
Event RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
Starting new HTTP connection (1): n95cloud.vip:80
http://n95cloud.vip:80 "GET / HTTP/1.1" 301 162
Starting new HTTPS connection (1): n95cloud.vip:443
https://n95cloud.vip:443 "GET / HTTP/1.1" 200 None
http://n95cloud.vip:80 "POST //auth/login HTTP/1.1" 301 162
https://n95cloud.vip:443 "GET /auth/login HTTP/1.1" 404 548
http://n95cloud.vip:80 "POST //user/checkin HTTP/1.1" 301 162
https://n95cloud.vip:443 "GET /user/checkin HTTP/1.1" 404 548

END RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
Report RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722 Duration:42ms Memory:128MB MemUsage:21.9805MB

Summary:
  Request ID: 46b5db67-49c8-4799-8d7f-6b2872812722
  Run Duration: 42
  Bill Duration: 42
  Usage Memory: 21.98046875
  Invoke Result: -1
```

**Comment by ne-21** [comment]
> 机场地址: [n95cloud.vip](n95cloud.vip)
> 
> ```
> Response: 
> {"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 99, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 92, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 52, in checkin\n    msg = (response.json()).get('msg')\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430}
> 
> Output:
> START RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
> Event RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
> Starting new HTTP connection (1): n95cloud.vip:80
> http://n95cloud.vip:80 "GET / HTTP/1.1" 301 162
> Starting new HTTPS connection (1): n95cloud.vip:443
> https://n95cloud.vip:443 "GET / HTTP/1.1" 200 None
> http://n95cloud.vip:80 "POST //auth/login HTTP/1.1" 301 162
> https://n95cloud.vip:443 "GET /auth/login HTTP/1.1" 404 548
> http://n95cloud.vip:80 "POST //user/checkin HTTP/1.1" 301 162
> https://n95cloud.vip:443 "GET /user/checkin HTTP/1.1" 404 548
> 
> END RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722
> Report RequestId: 46b5db67-49c8-4799-8d7f-6b2872812722 Duration:42ms Memory:128MB MemUsage:21.9805MB
> 
> Summary:
>   Request ID: 46b5db67-49c8-4799-8d7f-6b2872812722
>   Run Duration: 42
>   Bill Duration: 42
>   Usage Memory: 21.98046875
>   Invoke Result: -1
> ```


ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
国内IP无法访问

**Comment by jiangzhe11** [comment]
谢谢。腾讯云选择的是香港的服务器，需要新加坡的或者硅谷的吗？

**Comment by ne-21** [comment]
> 谢谢。腾讯云选择的是香港的服务器，需要新加坡的或者硅谷的吗？

香港应该可以
