### ISSUE TITLE
期望大佬更新下server酱Trubo版本支持企业微信转发的内容推送接口

### ISSUE THREAD

**Issue by osxhu** [ne-21/sspanel-automaticcheckin#15]
目前云函数多个机场的自动checkin运行良好~
关注到今天server酱上线了企业微信机器人推送这个功能，重点是可以支持个人微信接受完整消息，看了下还挺方便的，希望大佬有空搞下新的推送接口呗，谢谢啦~预祝happy new year!
附上一些我看到有用的介绍：

gzh文章：https://mp.weixin.qq.com/s/IWrOncAqBpRVCJEHjbjbIA

server酱消息通道：https://sct.ftqq.com/forward

企业微信配置教程：
https://work.weixin.qq.com/help?doc_id=13376#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%BE%A4%E6%9C%BA%E5%99%A8%E4%BA%BA

**Comment by ne-21** [comment]
> 目前云函数多个机场的自动checkin运行良好~
> 关注到今天server酱上线了企业微信机器人推送这个功能，重点是可以支持个人微信接受完整消息，看了下还挺方便的，希望大佬有空搞下新的推送接口呗，谢谢啦~预祝happy new year!
> 附上一些我看到有用的介绍：
> 
> gzh文章：https://mp.weixin.qq.com/s/IWrOncAqBpRVCJEHjbjbIA
> 
> server酱消息通道：https://sct.ftqq.com/forward
> 
> 企业微信配置教程：
> https://work.weixin.qq.com/help?doc_id=13376#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%BE%A4%E6%9C%BA%E5%99%A8%E4%BA%BA

已添加
