### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by kanxianbei** [ne-21/sspanel-automaticcheckin#16]
![image](https://user-images.githubusercontent.com/57819750/108508890-788e1c80-72f7-11eb-9785-4ab7c5a6dbb1.png)
老哥，测试一下出现这个结果怎么回事，按你说的把超时时间改成900也是这样

**Comment by ne-21** [comment]
> ![image](https://user-images.githubusercontent.com/57819750/108508890-788e1c80-72f7-11eb-9785-4ab7c5a6dbb1.png)
> 老哥，测试一下出现这个结果怎么回事，按你说的把超时时间改成900也是这样

可以提供下机场地址吗？有些机场国内IP访问不了，所以就报错了

**Comment by kanxianbei** [comment]
> > ![图像](https://user-images.githubusercontent.com/57819750/108508890-788e1c80-72f7-11eb-9785-4ab7c5a6dbb1.png)
> > 老哥，测试一下出现这个结果怎么回事，按你说的把超时时间改成900也是这样
> 
> 可以提供下机场地址吗？有些机场国内IP访问不了，所以就报

**Comment by kanxianbei** [comment]
就跑路云

**Comment by ne-21** [comment]
> 就跑路云

你可以看下我的配置
![QQ截图20210220184603.png](http://pic.521daigua.cn/2021/02/20/9ddff15e7c080.png)

**Comment by kanxianbei** [comment]
> > 就跑路云
> 
> 你可以看下我的配置
> ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)

还是不行，不过我看他上边显示有一个问题是这样的
![image](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)
什么意思

**Comment by Liujishou** [comment]
> > > 就跑路云
> > 
> > 
> > 你可以看下我的配置
> > ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)
> 
> 还是不行，不过我看他上边显示有一个问题是这样的的 英文意思
> ![图像](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)

我也是出现这个出错，不过我测试成功，只是我今天已经签到了 等明天看看是否能自动签到！

**Comment by ne-21** [comment]
> > > 就跑路云
> > 
> > 
> > 你可以看下我的配置
> > ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)
> 
> 还是不行，不过我看他上边显示有一个问题是这样的
> ![image](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)
> 什么意思

这个不影响，你换下运行区域看看，我用的上海

**Comment by ne-21** [comment]
> > > > 就跑路云
> > > 
> > > 
> > > 你可以看下我的配置
> > > ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)
> > 
> > 
> > 还是不行，不过我看他上边显示有一个问题是这样的的 英文意思
> > ![图像](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)
> 
> 我也是出现这个出错，不过我测试成功，只是我今天已经签到了 等明天看看是否能自动签到！

这个没影响

**Comment by kanxianbei** [comment]
> > > > 就跑路云
> > > 
> > > 
> > > 你可以看下我的配置
> > > ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)
> > 
> > 
> > 还是不行，不过我看他上边显示有一个问题是这样的
> > ![image](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)
> > 什么意思
> 
> 这个不影响，你换下运行区域看看，我用的上海

换成上海成功了，谢谢老哥指点

**Comment by ne-21** [comment]
> > > > > 就跑路云
> > > > 
> > > > 
> > > > 你可以看下我的配置
> > > > ![QQ截图20210220184603.png](https://camo.githubusercontent.com/0a270b2de5ea43c6e862e0264b86575697c443135e8d58ac6dce6b182c6b5006/687474703a2f2f7069632e3532316461696775612e636e2f323032312f30322f32302f396464666631356537633038302e706e67)
> > > 
> > > 
> > > 还是不行，不过我看他上边显示有一个问题是这样的
> > > ![image](https://user-images.githubusercontent.com/57819750/108593421-8baff380-73ae-11eb-9a14-7ccec17b7919.png)
> > > 什么意思
> > 
> > 
> > 这个不影响，你换下运行区域看看，我用的上海
> 
> 换成上海成功了，谢谢老哥指点

不客气
