### ISSUE TITLE
在魔戒官网里没看到签到位置呢？

### ISSUE THREAD

**Issue by supergming** [ne-21/sspanel-automaticcheckin#19]
之前跑路云签到云函数好用，前几天跑路云提示我账号过期了，不能用了，。想用魔戒，结果把配置文件里的地址换成魔戒的，但报错。
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 97, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 90, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 52, in checkin\n    msg = (response.json()).get('msg')\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430}

**Comment by ne-21** [comment]
> 之前跑路云签到云函数好用，前几天跑路云提示我账号过期了，不能用了，。想用魔戒，结果把配置文件里的地址换成魔戒的，但报错。
> {"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 97, in main_handler\n run.main()\n File "/var/user/index.py", line 90, in main\n msg = self.checkin()\n File "/var/user/index.py", line 52, in checkin\n msg = (response.json()).get('msg')\n File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 897, in json\n return complexjson.loads(self.text, **kwargs)\n File "/var/lang/python3/lib/python3.6/json/**init**.py", line 354, in loads\n return _default_decoder.decode(s)\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode\n raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","statusCode":430}

魔戒没有签到送流量活动
