### ISSUE TITLE
腾讯云函数报错

### ISSUE THREAD

**Issue by qing-niao** [ne-21/sspanel-automaticcheckin#2]
机场是 https://cccat.io/ 这个，主题是https://github.com/orvice/ss-panel/tree/v2
以下是日志
![image](https://user-images.githubusercontent.com/34891544/93656710-e095b980-fa5e-11ea-8e2a-84c5d6ad096c.png)

**Comment by ne-21** [comment]
> 机场是 https://cccat.io/ 这个，主题是https://github.com/orvice/ss-panel/tree/v2
> 以下是日志
> ![image](https://user-images.githubusercontent.com/34891544/93656710-e095b980-fa5e-11ea-8e2a-84c5d6ad096c.png)

因为有登陆验证，所以无法登录导致报错

**Comment by a5234338** [comment]
<img width="1177" alt="Snipaste_2020-12-18_21-22-25" src="https://user-images.githubusercontent.com/29723821/102619838-06bf1880-4178-11eb-96bb-30408b221d5c.png">
我这个没有登陆验证啊，不知道咋回事，你的帖子反复看都翻烂了也没能成。求大佬帮忙看看，感谢。

**Comment by a5234338** [comment]
@ne-21 求大佬帮忙。谢谢🙏
