### ISSUE TITLE
错误提示，

### ISSUE THREAD

**Issue by infoma990** [ne-21/sspanel-automaticcheckin#20]
日志:

START RequestId:812a3b55-7aaa-4567-a33c-d963bf991781

ERROR RequestId:812a3b55-7aaa-4567-a33c-d963bf991781 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 160, in get_func_handler\n    return getattr(mod, fname)\nAttributeError: module 'sspanel_qd' has no attribute 'py'","statusCode":443}

END RequestId:812a3b55-7aaa-4567-a33c-d963bf991781

Report RequestId:812a3b55-7aaa-4567-a33c-d963bf991781 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by infoma990** [comment]
复制code，更改自己的信息；提示网址不能打开
**START RequestId:36db106e-94df-44a9-8c45-7f183b07846a

Starting new HTTPS connection (1): www.mojie.me:443

https://www.mojie.me:443 "GET / HTTP/1.1" 200 None

https://www.mojie.me:443 "POST / HTTP/1.1" 405 None

https://www.mojie.me:443 "POST / HTTP/1.1" 405 None

网址不正确或网站禁止访问。

Response RequestId:36db106e-94df-44a9-8c45-7f183b07846a RetMsg:null

END RequestId:36db106e-94df-44a9-8c45-7f183b07846a

Report RequestId:36db106e-94df-44a9-8c45-7f183b07846a Duration:3071ms Memory:64MB MemUsage:16.078125MB**

**Comment by ICEOOX** [comment]
我也是同样的提示

**Comment by ne-21** [comment]
> 复制code，更改自己的信息；提示网址不能打开
> **START RequestId:36db106e-94df-44a9-8c45-7f183b07846a
> 
> Starting new HTTPS connection (1): [www.mojie.me:443](http://www.mojie.me:443)
> 
> https://www.mojie.me:443 "GET / HTTP/1.1" 200 None
> 
> https://www.mojie.me:443 "POST / HTTP/1.1" 405 None
> 
> https://www.mojie.me:443 "POST / HTTP/1.1" 405 None
> 
> 网址不正确或网站禁止访问。
> 
> Response RequestId:36db106e-94df-44a9-8c45-7f183b07846a RetMsg:null
> 
> END RequestId:36db106e-94df-44a9-8c45-7f183b07846a
> 
> Report RequestId:36db106e-94df-44a9-8c45-7f183b07846a Duration:3071ms Memory:64MB MemUsage:16.078125MB**

魔戒没有签到送流量活动

**Comment by ne-21** [comment]
> 我也是同样的提示

魔戒没有签到送流量活动

**Comment by infoma990** [comment]
感谢大佬回复帮助，明白了！
