### ISSUE TITLE
如果有时间，希望增加下其它推送消息平台

### ISSUE THREAD

**Issue by ICEOOX** [ne-21/sspanel-automaticcheckin#21]
Server酱新版免费版限制每天才5条，只有标题没有内容
我觉得是不是可以增加下其它推送？比如钉钉推送，BARK推送

**Comment by ne-21** [comment]
> Server酱新版免费版限制每天才5条，只有标题没有内容
> 我觉得是不是可以增加下其它推送？比如钉钉推送，BARK推送

您可以选择尝试使用Server酱Trubo版

**Comment by luoli8** [comment]
> > Server酱新版免费版限制每天才5条，只有标题没有内容
> > 我觉得是不是可以增加下其它推送？比如钉钉推送，BARK推送
> 
> 您可以选择尝试Qmsg

不用了，我自己写上了
