### ISSUE TITLE
云函数报错

### ISSUE THREAD

**Issue by delwte** [ne-21/sspanel-automaticcheckin#3]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 99, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 92, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 52, in checkin\n    msg = (response.json()).get('msg')\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}

日志:

START RequestId: 48997918-2977-4be5-b84b-d70bb91da29e

Event RequestId: 48997918-2977-4be5-b84b-d70bb91da29e

Starting new HTTPS connection (1): paoluz.net:443

https://paoluz.net:443 "GET /user HTTP/1.1" 302 None

https://paoluz.net:443 "GET /auth/login HTTP/1.1" 200 None

https://paoluz.net:443 "POST /user/auth/login HTTP/1.1" 302 None

https://paoluz.net:443 "GET /404 HTTP/1.1" 200 None

https://paoluz.net:443 "POST /user/user/checkin HTTP/1.1" 302 None

https://paoluz.net:443 "GET /404 HTTP/1.1" 200 None

 

ERROR RequestId:48997918-2977-4be5-b84b-d70bb91da29e Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 99, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 92, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 52, in checkin\n    msg = (response.json()).get('msg')\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"} 

END RequestId: 48997918-2977-4be5-b84b-d70bb91da29e

Report RequestId: 48997918-2977-4be5-b84b-d70bb91da29e Duration:5244ms Memory:256MB MemUsage:19.371094MB

**Comment by ne-21** [comment]
你网址填错了，看下图
![0tmpgH.png](https://s1.ax1x.com/2020/10/05/0tmpgH.png)

**Comment by ne-21** [comment]
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 99, in main_handler\n run.main()\n File "/var/user/index.py", line 92, in main\n msg = self.checkin()\n File "/var/user/index.py", line 52, in checkin\n msg = (response.json()).get('msg')\n File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 897, in json\n return complexjson.loads(self.text, **kwargs)\n File "/var/lang/python3/lib/python3.6/json/**init**.py", line 354, in loads\n return _default_decoder.decode(s)\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode\n raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
> 
> 日志:
> 
> START RequestId: 48997918-2977-4be5-b84b-d70bb91da29e
> 
> Event RequestId: 48997918-2977-4be5-b84b-d70bb91da29e
> 
> Starting new HTTPS connection (1): paoluz.net:443
> 
> https://paoluz.net:443 "GET /user HTTP/1.1" 302 None
> 
> https://paoluz.net:443 "GET /auth/login HTTP/1.1" 200 None
> 
> https://paoluz.net:443 "POST /user/auth/login HTTP/1.1" 302 None
> 
> https://paoluz.net:443 "GET /404 HTTP/1.1" 200 None
> 
> https://paoluz.net:443 "POST /user/user/checkin HTTP/1.1" 302 None
> 
> https://paoluz.net:443 "GET /404 HTTP/1.1" 200 None
> 
> ERROR RequestId:48997918-2977-4be5-b84b-d70bb91da29e Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 99, in main_handler\n run.main()\n File "/var/user/index.py", line 92, in main\n msg = self.checkin()\n File "/var/user/index.py", line 52, in checkin\n msg = (response.json()).get('msg')\n File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 897, in json\n return complexjson.loads(self.text, **kwargs)\n File "/var/lang/python3/lib/python3.6/json/**init**.py", line 354, in loads\n return _default_decoder.decode(s)\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode\n raise JSONDecodeError("Expecting value", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
> 
> END RequestId: 48997918-2977-4be5-b84b-d70bb91da29e
> 
> Report RequestId: 48997918-2977-4be5-b84b-d70bb91da29e Duration:5244ms Memory:256MB MemUsage:19.371094MB

你网址填错了，看下图
![0tmpgH.png](https://s1.ax1x.com/2020/10/05/0tmpgH.png)
