### ISSUE TITLE
云函数调用失败

### ISSUE THREAD

**Issue by zy777777** [ne-21/sspanel-automaticcheckin#4]
但是日志里能看到已签到的结果 
返回数据:

{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds"}

日志:

START RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8

Event RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8

Starting new HTTPS connection (1): www.cordcloud.site:443

https://www.cordcloud.site:443 "GET / HTTP/1.1" 200 None

https://www.cordcloud.site:443 "POST /auth/login HTTP/1.1" 200 None

https://www.cordcloud.site:443 "POST /user/checkin HTTP/1.1" 200 None

您似乎已经续命过了...

 

ERROR RequestId:df249d31-ebe1-497f-a8a9-15e6bed04ae8 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds"} 

END RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8

Report RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8 Duration:3000ms Memory:128MB MemUsage:19.625000MB

**Comment by ne-21** [comment]
Invoking task timed out after 3 seconds

> 但是日志里能看到已签到的结果
> 返回数据:
> 
> {"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds"}
> 
> 日志:
> 
> START RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8
> 
> Event RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8
> 
> Starting new HTTPS connection (1): [www.cordcloud.site:443](http://www.cordcloud.site:443)
> 
> https://www.cordcloud.site:443 "GET / HTTP/1.1" 200 None
> 
> https://www.cordcloud.site:443 "POST /auth/login HTTP/1.1" 200 None
> 
> https://www.cordcloud.site:443 "POST /user/checkin HTTP/1.1" 200 None
> 
> 您似乎已经续命过了...
> 
> ERROR RequestId:df249d31-ebe1-497f-a8a9-15e6bed04ae8 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds"}
> 
> END RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8
> 
> Report RequestId: df249d31-ebe1-497f-a8a9-15e6bed04ae8 Duration:3000ms Memory:128MB MemUsage:19.625000MB

可能是函数运行超时了
请按下图设置
![0gIMm6.png](https://s1.ax1x.com/2020/10/11/0gIMm6.png)

**Comment by zy777777** [comment]
这样设置可以了
