### ISSUE TITLE
发现一个机场不能正常签到

### ISSUE THREAD

**Issue by sundxr** [ne-21/sspanel-automaticcheckin#5]
https://j01.best
几鸡 域名还有j01.space
查看staff页面发现这个机场也是使用了ss-panel但是好像进行了魔改导致不能正常登陆签到
（测试可以正常进行其他几个机场的签到，所以我这边配置应该没有问题）
感谢您的贡献，吾爱由您更精彩。

**Comment by ne-21** [comment]
> https://j01.best
> 几鸡 域名还有j01.space
> 查看staff页面发现这个机场也是使用了ss-panel但是好像进行了魔改导致不能正常登陆签到
> （测试可以正常进行其他几个机场的签到，所以我这边配置应该没有问题）
> 感谢您的贡献，吾爱由您更精彩。

我在官网点击签到都没反应。。

**Comment by sundxr** [comment]
> > https://j01.best
> > 几鸡 域名还有j01.space
> > 查看staff页面发现这个机场也是使用了ss-panel但是好像进行了魔改导致不能正常登陆签到
> > （测试可以正常进行其他几个机场的签到，所以我这边配置应该没有问题）
> > 感谢您的贡献，吾爱由您更精彩。
> 
> 我在官网点击签到都没反应。。
这个机场要绑定个人信息后点签到才正常，就很离谱

**Comment by ne-21** [comment]
> > > https://j01.best
> > > 几鸡 域名还有j01.space
> > > 查看staff页面发现这个机场也是使用了ss-panel但是好像进行了魔改导致不能正常登陆签到
> > > （测试可以正常进行其他几个机场的签到，所以我这边配置应该没有问题）
> > > 感谢您的贡献，吾爱由您更精彩。
> > 
> > 
> > 我在官网点击签到都没反应。。
> > 这个机场要绑定个人信息后点签到才正常，就很离谱

这未免也太墨迹了吧
