### ISSUE TITLE
MmmAagic 主题好像不能正常签到

### ISSUE THREAD

**Issue by mozro0327** [ne-21/sspanel-automaticcheckin#6]
机场是这个 freemycloud.pw
![image](https://user-images.githubusercontent.com/53436640/97705373-efa46880-1aee-11eb-833e-860e75da871b.png)

**Comment by ne-21** [comment]
> 机场是这个 freemycloud.pw
> ![image](https://user-images.githubusercontent.com/53436640/97705373-efa46880-1aee-11eb-833e-860e75da871b.png)

可能是函数运行超时了
请按下图设置
![0gIMm6.png](https://s1.ax1x.com/2020/10/11/0gIMm6.png)
