### ISSUE TITLE
这说明意思

### ISSUE THREAD

**Issue by bdzcan77** [ne-21/sspanel-automaticcheckin#7]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 99, in main_handler\n    run.main()\n  File \"/var/user/index.py\", line 92, in main\n    msg = self.checkin()\n  File \"/var/user/index.py\", line 34, in checkin\n    session.get(self.base_url, verify=False)\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py\", line 546, in get\n    return self.request('GET', url, **kwargs)\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py\", line 519, in request\n    prep = self.prepare_request(req)\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py\", line 462, in prepare_request\n    hooks=merge_hooks(request.hooks, self.hooks),\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 313, in prepare\n    self.prepare_url(url, params)\n  File \"/var/lang/python3/lib/python3.6/site-packages/requests/models.py\", line 387, in prepare_url\n    raise MissingSchema(error)\nrequests.exceptions.MissingSchema: Invalid URL 'freemycloud.pw': No schema supplied. Perhaps you meant http://freemycloud.pw?"}

**Comment by ne-21** [comment]
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 99, in main_handler\n run.main()\n File "/var/user/index.py", line 92, in main\n msg = self.checkin()\n File "/var/user/index.py", line 34, in checkin\n session.get(self.base_url, verify=False)\n File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 546, in get\n return self.request('GET', url, **kwargs)\n File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 519, in request\n prep = self.prepare_request(req)\n File "/var/lang/python3/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request\n hooks=merge_hooks(request.hooks, self.hooks),\n File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 313, in prepare\n self.prepare_url(url, params)\n File "/var/lang/python3/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url\n raise MissingSchema(error)\nrequests.exceptions.MissingSchema: Invalid URL 'freemycloud.pw': No schema supplied. Perhaps you meant [http://freemycloud.pw?"}](http://freemycloud.pw?%22%7D)

本人测试无问题
![QQ截图20201106195248.png](https://i.loli.net/2020/11/06/lHNIJq7fPaRAYgB.png)

**Comment by bdzcan77** [comment]
大佬，我小白。。下了仓库，选的Python 3.6空白函数，然后怎么弄？“提示将sspanel_qd.py上传到腾讯云函数”这一步我迷了。选文件夹提示我“在您选择的文件夹里面找不到sspanel-automaticcheckin-master/index.py文件”
